global:
  scrape_interval: 30s
  scrape_timeout: 10s

scrape_configs:
  - job_name: caddy
    metrics_path: /metrics
    static_configs:
      - targets:
          - localhost:2019

  - job_name: backcat
    metrics_path: /api/extra/metrics
    static_configs:
      - targets:
          - backcat_server:8080

  - job_name: cadvisor
    metrics_path: /metrics
    static_configs:
      - targets:
          - cadvisor:8080

  - job_name: node_exporter
    metrics_path: /metrics
    static_configs:
      - targets:
          - node_exporter:9100

  - job_name: prometheus
    metrics_path: /metrics
    static_configs:
      - targets:
          - localhost:9090
